version: 2
updates:
  - package-ecosystem: nuget
    directory: "/"
    schedule:
      interval: weekly
      day: monday
    groups:
      microsoft-extensions:
        patterns:
          - "Microsoft.Extensions.*"
        update-types:
          - minor
          - patch
    open-pull-requests-limit: 5
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 3
